### ISSUE TITLE
Ultra Difficult

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#113]
Please remove this spinner <http://jack-frost.is-pretty.cool/9p7XkYk.png>. It causes you to, even if you do the dream hyper correctly, still die to something that is nearly impossible to control. See: <http://jack-frost.is-pretty.cool/9vw2m1c.mp4>
Submitted by Yoshi

**Comment by Habbedaz** [comment]
Copying from discord:

The entire point of that section is to control your positioning to allow for a dreamhyper, that is a very preventable death. I don't think it should be removed.

You can go earlier than that too and still be able to execute a dreamhyper, but die to the dreamblock. It's not supposed to be a lenient dreamhyper, nor is it supposed to be a case of "execute and you're good." You're supposed to die to the spinner or the dreamblock and realise you can control Madeline's positioning to prevent it.

Even with the option of dying to that, it's still a very lenient dreamhyper if you downleft later or hyper later on coyote. In my run you can even see me get more or less the same positioning, but consciously go later on coyote to avoid a death because I realised I messed up.

This entire map is about on-the-spot decisions. It's not supposed to be exclusively execution based.
