### ISSUE TITLE
FlagTouchSwitch breaks when used outside map (e.g. randomizer)

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#195]
Not sure whether or not to classify as a bug considering this was made to be collab specific. The touch switches are tracked within a list called SpringCollab2020MapDataProcessor.FlagTouchSwitches[AreaID][ModeID][flagName]. Obviously a randomizer-created level's AreaID is not in the list, so when you touch the switch and it tries to access the list with that index it crashes... Could this be changed to be more level-agnostic? It's just checking the session flags for a specific area, so do these really need to be specifically stored? Or could DynData<Session> be used instead?
Submitted by Bigkahuna

**Comment by maddie480** [comment]
After discussion, a good solution for the randomizer is to just add a bounds check so that if the list isn't defined for the current map, the touch switch will assume all matching switches are in the current room. Touch switches that affect other rooms won't work well with the randomizer anyway. 😅 

This has been addressed in https://github.com/EverestAPI/SpringCollab2020/commit/aae2f700fad27dd200f3dfd26b39fa9a5bc08ef4
