### ISSUE TITLE
Silver berry deaths

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#281]
Silver berries do not seem to set lowest deaths to 0 when collected. After returning to map after collecting the silver but before the level ends, the silver icon appears in the journal, but on the overworld journal death tally you can still see that you don't have 0 even with all silvers.
Submitted by dog

**Comment by maddie480** [comment]
Should be fixed in https://github.com/EverestAPI/CelesteCollabUtils2/commit/d9e70141f02d7a565c5aaf5a6be3c23cbb6c4704 (both for the overworld journal, and the total displayed in the lobby journal).

I also noticed the golden berry icon that was supposed to show up in the overworld journal when you got all silvers and the golden for a difficulty didn't show up; this is fixed in https://github.com/EverestAPI/CelesteCollabUtils2/commit/bdccd4c73a3047f1113b394256871156078abc79
